const NguoiDungController = require('../controller/NguoiDungController');
const authMiddleware = require('../middlewares/authMiddleware');
const nguoiDungRouter = require('express').Router();
nguoiDungRouter.post('/', NguoiDungController.register);
nguoiDungRouter.post('/login', NguoiDungController.login);
nguoiDungRouter.post('/logout', NguoiDungController.logout);
nguoiDungRouter.get('/check', authMiddleware, NguoiDungController.check);
nguoiDungRouter.get('/', NguoiDungController.getAllUsers);
nguoiDungRouter.put('/:id', NguoiDungController.updateUser);
nguoiDungRouter.delete('/:id', NguoiDungController.deleteUser);
nguoiDungRouter.get('/me', authMiddleware, NguoiDungController.getMe);
nguoiDungRouter.put('/capnhat/:id', NguoiDungController.updateUser);
nguoiDungRouter.get('/vaitro', NguoiDungController.getUserByRole);
nguoiDungRouter.get('/:id', NguoiDungController.getUserById);
module.exports = nguoiDungRouter;
